DOMAIN_CONFIG = {
    "Agriculture": {
        "freq_type": "monthly",
        "csv": "Agriculture/Agriculture.csv",
        "seq_len": 8,
        "label_len": 4,
        "pred_lens": [6, 8, 10, 12],
    },
    "Climate": {
        "freq_type": "monthly",
        "csv": "Climate/Climate.csv",
        "seq_len": 8,
        "label_len": 4,
        "pred_lens": [6, 8, 10, 12],
    },
    "Economy": {
        "freq_type": "monthly",
        "csv": "Economy/Economy.csv",
        "seq_len": 8,
        "label_len": 4,
        "pred_lens": [6, 8, 10, 12],
    },
    "Energy": {
        "freq_type": "weekly",
        "csv": "Energy/Energy.csv",
        "seq_len": 36,
        "label_len": 18,
        "pred_lens": [12, 24, 36, 48],
    },
    "Environment": {
        "freq_type": "daily",
        "csv": "Environment/Environment.csv",
        "seq_len": 96,
        "label_len": 48,
        "pred_lens": [48, 96, 192, 336],
    },
    "Health_US": {
        "freq_type": "weekly",
        "csv": "Health_US/Health_US.csv",
        "seq_len": 36,
        "label_len": 18,
        "pred_lens": [12, 24, 36, 48],
    },
    "Security": {
        "freq_type": "monthly",
        "csv": "Security/Security.csv",
        "seq_len": 8,
        "label_len": 4,
        "pred_lens": [6, 8, 10, 12],
    },
    "SocialGood": {
        "freq_type": "monthly",
        "csv": "SocialGood/SocialGood.csv",
        "seq_len": 8,
        "label_len": 4,
        "pred_lens": [6, 8, 10, 12],
    },
    "Traffic": {
        "freq_type": "monthly",        
        "csv": "Traffic/Traffic.csv",
        "seq_len": 8,
        "label_len": 4,
        "pred_lens": [6, 8, 10, 12],
    },
}